Fix a few small things
newlines get printed, so remove them

fix weird messages when no argument is given:
basename: missing operand
Try 'basename --help' for more information.
error: no devices/emulators found